config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #HTTPリクエスト名 'URLのディレクトリ部分' => 'コントローラー名#そのアクション'
  get 'top' => 'homes#top'

  get 'todolists/new'
  post 'todolists' => 'todolists#create'
  get 'todolists' => 'todolists#index'
  # .../todolists/1 や .../todolists/3 に該当する
  #as: '名前' は「名前付きルート」
  get 'todolists/:id' => 'todolists#show', as: 'todolist'
  get 'todolists/:id/edit' => 'todolists#edit', as: 'edit_todolist'
  #更新の場合はpatchメソッドを利用する.
  patch 'todolists/:id' => 'todolists#update', as: 'update_todolist'
  delete 'todolists/:id' => 'todolists#destroy', as: 'destroy_todolist'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  #refileが指定のカラムにアクセスするために必要
  #カラム名はimage+_idなので注意
  attachment :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end 
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  def new
    # Viewへ渡すためのインスタンス変数に空のモデルオブジェクトを生成する。
    #@は対象拡張子と呼ばれスコープを拡大する.@がついているものはインスタンス変数と呼ばれる.
    @list = List.new
  end

  def create
    # ストロングパラメーターを使用
     list = List.new(list_params)
    # DBへ保存する
     list.save
    # 詳細画面にリダイレクト
    redirect_to todolist_path(list.id)
  end

  def index
    #新しくlistsインスタンスを作成する(配列)
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    #listを適宜更新する
    list = List.find(params[:id]) #インスタンス
    list.update(list_params) #DB
    redirect_to todolist_path(list.id)
  end

  def destroy
    list = List.find(params[:id]) #データ(レコード)を1件取得
    list.destroy #データ（レコード）を削除
    redirect_to todolists_path #List一覧画面へリダイレクト
  end

  private
  #publicなメソッドを定義してしまうとアクションと認識されてしまう
  #privateなメソッドの命名規則として,モデル名_paramsとされることが多い.
  def list_params
      #paramsって何
      #requireでオブジェクト指定
      #permitでformで指定されているオブジェクトを指定
      #ListってEntityが定義されていないけども…これでいけるのか.
      params.require(:list).permit(:title, :body, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/homes/top.html.erb
<h1>ここはTopページです</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todolists/edit.html.erb
<h1>編集画面</h1>
<!-- form_forにインスタンス変数を渡すことができる -->
<%= form_for(@list, url:"/todolists/#{@list.id}") do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title %>
    <h4>本文</h4>
    <%= f.text_area :body %>
    <%= f.submit '保存' %>
<% end %>

app/views/todolists/index.html.erb
<h1>投稿一覧</h1>
<!--　＝を付けないことで処理として扱う -->
<% @lists.each do |list| %>
  <p>タイトル</p>
  <span>
    <!--　名前付きルートを利用しているのでtodolists/:idをtodolistとして扱えて -->
    <%=link_to list.title, todolist_path(list.id) %>
    <!-- link_to list.title, "/todolists/#{list.id}" %> -->
  </span>
  <p>画像</p>
  <%= attachment_image_tag list, :image, :fill, 100, 100, format: 'jpeg' %>
<% end %>

app/views/todolists/new.html.erb
<h1>新規投稿</h1>
<!-- Rubyでは独自のタグが利用される.=がついている部分のみ画面に出力される. -->
<!-- form_for部分 -->
<%= form_for(@list, url: '/todolists') do |f| %>

    <h4>タイトル</h4>
    <%= f.text_field :title %>

    <h4>本文</h4>
    <%= f.text_area :body %>

    <%= f.submit '投稿' %>

    <!-- 追加部分 -->
    <h4>画像</h4>
    <%= f.attachment_field :image %>

<% end %>

app/views/todolists/show.html.erb
<h2>タイトル</h2>
<p><%= @list.title %></p>
<h2>本文</h2>
<p><%= @list.body %></p>
<h2>画像</h2>
<%= attachment_image_tag @list, :image, :fill, 300, 300, format: 'jpeg' %>

<%= link_to "編集", edit_todolist_path(@list.id) %>
<%= link_to "削除", destroy_todolist_path(@list.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>